FROM nginx:alpine

# Créer une page simple
RUN echo '<html><body><h1>🚀 FIT Platform v3.0</h1><p>Successfully deployed on fit.tbhc.uk!</p><p>Date: '$(date)'</p></body></html>' > /usr/share/nginx/html/index.html

# Configuration nginx pour le port dynamique
RUN echo 'server { listen $PORT; location / { root /usr/share/nginx/html; index index.html; } }' > /etc/nginx/conf.d/default.conf.template

# Script de démarrage
RUN echo '#!/bin/sh\nenvsubst '\''$PORT'\'' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf\nnginx -g "daemon off;"' > /start.sh && chmod +x /start.sh

EXPOSE 8080

CMD ["/start.sh"]
