import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    safelist: [
        'font-sans',
        'antialiased',
        'min-h-screen',
        'bg-gradient-to-br',
        'from-blue-600',
        'to-purple-700',
        'max-w-6xl',
        'mx-auto',
        'px-8',
        'py-12',
        'text-center',
        'text-white',
        'mb-12',
        'text-5xl',
        'font-bold',
        'mb-4',
        'text-xl',
        'opacity-90',
        'bg-white',
        'rounded-xl',
        'shadow-2xl',
        'p-8',
        'mb-8',
        'text-2xl',
        'font-semibold',
        'text-gray-800',
        'mb-6',
        'space-y-3',
        'flex',
        'items-center',
        'text-gray-700',
        'w-3',
        'h-3',
        'bg-green-500',
        'rounded-full',
        'mr-3',
        'grid',
        'grid-cols-1',
        'md:grid-cols-3',
        'gap-8',
        'text-lg',
        'font-semibold',
        'text-gray-800',
        'mb-4',
        'text-gray-600',
        'leading-relaxed',
        'flex-wrap',
        'justify-center',
        'gap-4',
        'inline-flex',
        'items-center',
        'px-6',
        'py-3',
        'bg-blue-600',
        'text-white',
        'font-medium',
        'rounded-lg',
        'hover:bg-blue-700',
        'transition-colors',
        'duration-200',
        'transform',
        'hover:-translate-y-1',
        // Additional classes that might be missing
        'text-3xl',
        'text-4xl',
        'text-6xl',
        'text-7xl',
        'text-8xl',
        'text-9xl',
        'text-sm',
        'text-base',
        'text-lg',
        'text-xl',
        'text-2xl',
        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-extrabold',
        'font-black',
        'bg-blue-500',
        'bg-blue-700',
        'bg-blue-800',
        'bg-blue-900',
        'bg-purple-500',
        'bg-purple-600',
        'bg-purple-800',
        'bg-purple-900',
        'text-blue-500',
        'text-blue-600',
        'text-blue-700',
        'text-blue-800',
        'text-blue-900',
        'text-purple-500',
        'text-purple-600',
        'text-purple-700',
        'text-purple-800',
        'text-purple-900',
        'rounded',
        'rounded-sm',
        'rounded-md',
        'rounded-lg',
        'rounded-xl',
        'rounded-2xl',
        'rounded-3xl',
        'rounded-full',
        'shadow',
        'shadow-sm',
        'shadow-md',
        'shadow-lg',
        'shadow-xl',
        'shadow-2xl',
        'shadow-inner',
        'shadow-none'
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
